sudo: false

language: node_js
node_js:
  - "7.6.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

install:
  - npm install -g cordova ionic
  - npm install

before_script:
  - wget --quiet http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter --silent platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter --silent build-tools-26.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter --silent android-26
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter --silent extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter --silent extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter --silent extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/26.0.2

script:
  - ionic cordova build --release android
  - mv /home/travis/build/jordanmarques/jlearn/platforms/android/build/outputs/apk/release/android-release-unsigned.apk /home/travis/build/jordanmarques/jlearn/platforms/android/build/outputs/apk/release/jlearn-unsigned.apk

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_KEY
  file: /home/travis/build/jordanmarques/jlearn/platforms/android/build/outputs/apk/release/jlearn-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
